version: 1

deployment:
  name: {{ name }}
  tag: {{ tag }}
  region: {{ region }}
  sshKeys:
    {{#sshKeys}}
    - {{.}}
    {{/sshKeys}}

application:
  buildpack: {{ buildpack }}
  size: {{ size }}
  replicas: {{ replicas }}

services:
  {{#loadbalancer}}
  - kind: loadbalancer
    healthcheck: /
    rules:
      - protocol: http
        port: 80
        targetPort: 3000
      - protocol: https
        port: 443
        targetPort: 3000
  {{/loadbalancer}}
